export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_CHECK = 'AUTH_CHECK';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const PATIENT_SEARCH = 'PATIENT_SEARCH';
export const PATIENT_LIST = 'PATIENT_LIST';
export const PATIENT_INFO = 'PATIENT_INFO';

export const PATIENT_TESTS_LIST = 'PATIENT_TESTS_LIST';

export const PATIENT_APPOINTMENTS_LIST = 'PATIENT_APPOINTMENTS_LIST';

export const PATIENT_MESSAGES_LIST = 'PATIENT_MESSAGES_LIST';

export const TEST_ALL = 'TEST_ALL';
export const TEST_LIST = 'TEST_LIST';
export const TEST_INFO = 'TEST_INFO';
